version: 0.1.0.{build}

platform: x64

init:
  - git config --global core.autocrlf input

cache:
  - electron\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\APTrust\easy-store

environment:
  GOPATH: c:\gopath
  access_token:
    secure: pJmtCY7+qzctn9m6UejaJGlls3IMl8p2Tb3DjypHL+8DLmNNHK0jQZmZbb4sIJgM

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install --prefix ./electron electron-builder@next # force install next version to test electron-builder
  - cd electron && npm install
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%/electron/node_modules/.bin;%PATH%
  - go version
  - go env
  - go get golang.org/x/crypto/md4
  - go get github.com/satori/go.uuid

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\apps\apt_create_bag\ && go build .
  - npm run --prefix ./electron
  - cd %APPVEYOR_BUILD_FOLDER%/electron && electron-builder .

artifacts:
  - path: electron/dist/*.exe
    name: EasyStore-Windows

  - path: ${env.GOPATH}/bin/**
    name: Go-binaries

test: off
deploy:
  release: easy-store-$(appveyor_build_version)
  description: 'This is a test release of the windows build from CI'
  provider: GitHub
  auth_token:
    secure: pJmtCY7+qzctn9m6UejaJGlls3IMl8p2Tb3DjypHL+8DLmNNHK0jQZmZbb4sIJgM
    artifact: EasyStore-Windows, Go-binaries # This is the name we specified in the artifacts section.
  draft: true
  prerelease: false
  on:
    branch:
      - windows-build
      - master

notifications:
  - provider: Slack
    incoming_webhook:
      secure: wQc/CYuw0WsjVvpj92QtP6//CzBNp/eFYpvlxiH6lIdhCbrh+cgQ3vExTygXJFA3xPg0attMwE/dOWipSS+vsk0EGsf0iipIaf/133/1RgQ=
