version: 0.1.6.{build}

platform: x64

init:
  - git config --global core.autocrlf input

cache:
  - electron\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master

clone_folder: c:\gopath\src\github.com\APTrust\dart

environment:
  GOPATH: c:\gopath
  access_token:
    secure: "IMzd8tEL6AOY7a/xeeGCUEYjqyR8lSoXhn9h1s0WHFHnzpi6QevW/v0Jr/jZQpZuYyUkTILUUdvqrsjc4CpB2vomJPVghnAo2VmSDXXo+Ac="
  appveyor_repo_tag: true


install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install --prefix ./electron electron-builder@next # force install next version to test electron-builder
  - cd electron && npm install
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%/electron/node_modules/.bin;%PATH%
  - set GITREF=$(git log --format=%h -1)

build_script:
  - npm run --prefix ./electron
  - cd %APPVEYOR_BUILD_FOLDER%/electron && electron-builder .

artifacts:
  - path: electron/dist/*.exe
    name: DART-Windows

test: off
deploy:
  #release: dart-$(appveyor_build_version)
  release: dart-$(GITREF)
  description: 'This is a test release of the windows build from CI'
  provider: GitHub
  auth_token:
    secure: "aRmyb4MvUXixI0YxRrymu6tioWaonnxMq942M8IVd8TN9xp/8249Yvl5GxXy8mWs"
  artifact: DART-Windows
  draft: true
  prerelease: false

notifications:
  - provider: Slack
    incoming_webhook:
      secure: wQc/CYuw0WsjVvpj92QtP6//CzBNp/eFYpvlxiH6lIdhCbrh+cgQ3vExTygXJFA3xPg0attMwE/dOWipSS+vsk0EGsf0iipIaf/133/1RgQ=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
