os: osx
osx_image: xcode9.2
sudo: false
language: node_js
node_js: '9'
env:
  global:
   - ARTIFACTS_DEBUG=1
   - ARTIFACTS_KEY=(AWS access key id)
   - ARTIFACTS_SECRET=
 		secure: eOwbN81+m8xAntNpef0zDMrsz6ZzEry9ZRvnxjvL9izpo9IlIAPwlPtDrLMlAv9Nf1g1WJvAUt25NelSRoApLsBbSZohdyMyy0AlC+KiyXv6sHVMhzmZQ2WFPg/atQkg+WwxQsizRur2VWaqR0Ke2K0cFmlo0HZm+w3iEJt8Y8lGewsAe9AcHLoxd8hFtABnijfeHq0fUzzLSgpdme9UTDGgO3HSj7I4B01+Rfq00W5u3RPZVqqff8bErQKC+8ZAYC1HAgM3FnK/m+vzwNkOl6m9t5xiUiNXGCaCb3/zRR8ZH/snFup8xKJwikNfLlxGkEpkfH+mlcNzER3e3xRF3m2eZO410spoLa/9PkI5GRfv2ZX+tm8mNpqZjU5v1BHmsirdspzJ2uVTH456yM2RfS46M202OuX7W1i7HMmliRNRNgvvsYnNqgSxiPI2283xJxSmfn0UysuMe4he+zVM5SIqu6Bhx0zrrSw9oLP4vTCYjnzlNMFqDcxlsjLOfi1aCM8fxnEBCSupHbEMTIqSNfL7lMqhBiGbHp0CUVWuj37Z7BAjZLmvtndV25Ju3AnOOMybzk+6KpKZhGwdYQWnN48Z28r3kqKyZESdx44Z+LA8SxRuiOBqvL/R0qCcZfqATxvmW+aPkFj9cjASro92WWVR8niNg2v7aLXXH1GJIEQ=
ARTIFACTS_BUCKET=aptrust.public.download


cache:
  directories:
  - electron/node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.npm/_prebuilds"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
install:
- yarn
before_script:
- git lfs pull
stages:
  - name: run test for refactor only
    if: branch = refactor
      cd refactor && npm test
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn ; fi
- buildver="$(grep version electron/package.json |sed "s/[^0-9.]//g").$(git log --format=%h -1)"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder -p never --em.version=$buildver; fi


addons:
  artifacts:
    working_dir: dist
    paths:
     - $(git ls-files -o dist/{*.dmg,*.exe,*.deb} | tr "\n" ":")
    target_paths:
     - /app/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}$([ ! -z ${TRAVIS_TAG} ] && echo _tag-${TRAVIS_TAG})

deploy:
  provider: s3
  access_key_id: AKIAIN34AYPE5DX5EJUQ
  secret_access_key:
    secure: eOwbN81+m8xAntNpef0zDMrsz6ZzEry9ZRvnxjvL9izpo9IlIAPwlPtDrLMlAv9Nf1g1WJvAUt25NelSRoApLsBbSZohdyMyy0AlC+KiyXv6sHVMhzmZQ2WFPg/atQkg+WwxQsizRur2VWaqR0Ke2K0cFmlo0HZm+w3iEJt8Y8lGewsAe9AcHLoxd8hFtABnijfeHq0fUzzLSgpdme9UTDGgO3HSj7I4B01+Rfq00W5u3RPZVqqff8bErQKC+8ZAYC1HAgM3FnK/m+vzwNkOl6m9t5xiUiNXGCaCb3/zRR8ZH/snFup8xKJwikNfLlxGkEpkfH+mlcNzER3e3xRF3m2eZO410spoLa/9PkI5GRfv2ZX+tm8mNpqZjU5v1BHmsirdspzJ2uVTH456yM2RfS46M202OuX7W1i7HMmliRNRNgvvsYnNqgSxiPI2283xJxSmfn0UysuMe4he+zVM5SIqu6Bhx0zrrSw9oLP4vTCYjnzlNMFqDcxlsjLOfi1aCM8fxnEBCSupHbEMTIqSNfL7lMqhBiGbHp0CUVWuj37Z7BAjZLmvtndV25Ju3AnOOMybzk+6KpKZhGwdYQWnN48Z28r3kqKyZESdx44Z+LA8SxRuiOBqvL/R0qCcZfqATxvmW+aPkFj9cjASro92WWVR8niNg2v7aLXXH1GJIEQ=
  bucket: aptrust.public.download
  local-dir: dist
  upload-dir: DART
  acl: public_read
  skip_cleanup: true
  on:
    repo: APTrust/dart
