os: osx
language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - "$HOME/.npm/_prebuilds"
addons:
  homebrew:
    packages:
    - jq
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
install:
- npm install --global npm@latest
- rm -rf node_modules
- rm package-lock.json
- npm install
before_script:
- git lfs pull
- buildver="$(grep version package.json |sed "s/[^0-9.]//g").$(git log --format=%h
  -1)"
script:
- npm test -- --runInBand
- electron-builder . --publish never -m dmg --linux deb tar.gz
- "./jsdoc.sh"
notifications:
  slack:
    secure: fYGIkZMYp/HhRhi4/6Q1jpv0nWfpZaqaIKRhhloi+kBIt2fFun49LmTQfjqGLfwKKCKNmx8XzdIASUZuW7auJhHLUZPWaeEDxQjNVjrSOKOUuFUeGCKRJtw6+la0VxT79y5YIWxrnY2Noi8I6NvxniAJwnyQlHdyCnavmZzTA2xQGHxfTI4PR3ZkFt6lVAEC09NZMYwUf5+jsFmR6k/NGBU0jotDkfsm7AdzADSHwqfGvi70V9+muG4DIJejRVOkyCka2EOixbAyOOzbvrDwOo8tZVbY6Ch0LCfYndbDIztWXWb34R8LQEVKJA6QV2qMHmqSyMmR1RUO/OmMDmq+kM4C3M3D91knrugFVJiLJeowj8cb5LKgX35cd8/dHCDnLkSuaAw+rk5ny3TzfX2uh/EI9QN8y7S+er+QNvumy3M1+pkT+M+7t+auu0l7Ab+G/8W5X0PrZaQ+M933tYy1FC0zrp+CNs6BQnVvpql7REISJuuZ3T950FCxLM09XDGTnqxkgo8NrunuHcFgr8Jo74dl4TiixJteCVTOYI46KvfWDDlByKRmYb8GpQOXY4TT0dH5eEOjbcF3OFSQrx0aiC2TA6sTVHzvRqHdjjDGv2IXcJUJyLMnXrUsMVl4MuDCWGsqwKSEh71mflkreSc4yZ17M5ZEUBh90/dA9eICk9c=
env:
  global:
  - secure: yufxN+orgKMu4xSawX8oz6NeAtaTJSfOoTQuxGTI/W2vrkCadBu6p7yC2f7CiWGzGMzPCTG+HjT0+P6m1vFoFZgMZyFVvzGDA2Ec9exL3ZWZHwGVKm9C5SqiAzpzCZz7e5TBpv22hhBTP2JN0upNNd2KwN9sSpJUD5KNIMHLKYpbAl303y6po+sYkGKiw6WYZqPVpt27py6XLtgzlkj6LqGB4NP/uhQfxyRV9vXSFG6YenLBekKlYlSlaEMyvwezUthmyi9xyPSKLPg1xODayVlG7dXLEL6wjXjZQIWtokb2ogNCc9o47uDJbfesDfHingDhk4TYLDbF7TlE65mu2AToaPV7rZ5sPIJ4mhy7IO/jOPQiAgUFmky9rojfzOfGjSN6yMkuFbdnv1WnR6z/6kt4CfF4wHVoe2FLvZBGIE6TuIOdFG2LRSdoyZIK4cHLea3fVGHOLAS83V88gA72NOz+xNDKTvdBHSusNFrVSjjJq3m8mbGqg3shdzoi9/vUMgMh0nJ388TeSyKvchi0D3W3PfLWRy9FIEMV+TnSER4f83a02NIOtn2BVI2tSGzPbFDuzAlakq9nqklkX5WouyW791YcO/6tmP+V4ahFzX39NAgWguvqPEgwEOfG3JSvVDvMfGyoXyuoHvWPUD4aTWZ5lTITrJ3KiayYh/KoFiU=
  - secure: eXxUI/kBtBodrxBa7aLeGaO/1Xb3TLRV7CrcZYsuYFHlnGFZyPkgCrkE+AloNPtKuBJEwMyeg5DxQgBYHbLAorDp0Vl7Kgy/0NUvYOD9NWdi3zcnnZtb89Ob53VpfBp5z2eqaXzu+jFKIeyvIUHd1wWnsGWGxLs98+CK3ioWkXbtGuqkqlo7tHy9HXv5lgSzNldvPbLajxzv9JKhCq5moQ5hJabnoly7d1DCFGzhSObRRfjAWJevwQ/cVxWWBuv88R8+Dn3VAJecex4Z+BOwz/AY0YiqyglO9tytFSQkiWRiSR2M5c9xbTYxua8rgHEquUHTAwkEx3ND5lq2I7thr1Uote8nCyK7P1PuJg9CBq0ep3F0OF0S/D5g5MFIhUhDrUr2qDHdT+Ye0MIeyOHrGMjGyoG6Hs+S3nsvLgGoP/7kFyDJ2fJIfvZlHWR9BkKBrwvvJLuyLrVD63gTjwsFUwUmnHPTQ0INqAgur3Ih8RjpxLATJy+Cd5kkouVAabfyXmD8/ZAaFYK8Z39NsBEfUt1QvcSzwNQk/BRH3AGEd96Zg+qvVhQ3TmSrLBVbkU0/R4ol55u+D6z4T/J4eqU897UMa1XTen2oclxiVca0yCfw6F5cmGJRgaXATKGF1FcPtqdmI26ppTL9eVQmPMynTf9/IHOSo1/4Ow6dKyu19dE=
deploy:
  - provider: pages
    cleanup: false
    token: "$GH_TOKEN"
    keep_history: true
    verbose: true
    local_dir: docs
  - provider: s3
    access_key_id:
         secure: dt81k+9NpnkhzS1RXkMqjl5xrThstXrq4uxs9c4JmYpDl4tvK+EGvgil7FJZ0b3MKycP7cddTD5+sKbqaD3itc7BIt+WZJbhRq/pxPSg0WnRVVJ96dYzQGeTHao4MTzWwlUa90Q1c3VVNxcMWSG/9ICEPK0K1c91NPzIypdZLXMybAox/DfiokUJhq1grfa/jyRKFDMpXvYe+YurHKMbpxjQ+1d1cLyvb4ayVFcAYLBMgImwLOWNXYjDxyQzx5qwy5f8VMXPZt5IFgp5KbzFeupVrd5FaQgjOlAoGUJ5A80cnxO23I3FlfyNBMrRKt5zH2h0IaZrcxrKSkVBQPbqFQD5ceimUzU9GaNCdSSiUN91buqZDochuDqJivFunXWGDGaLC0KTYqrjjx/3EXhw6OiCKIY8atkMulenEZeLiGToE6EP/h7cP/P+X7ddiZOdxT66bLISO+/LEqCE51tPZFmVL3e2ZfQfT8L8n8InA63ge190BGptPheaAM0/l2WxIazbvYCtzNm7WDI8TKp6HMS/QfdywXDQc+gWbQbKjb9wg69GR8teypbg6Ns/ZbUpYtmYxHhzabe4SLLtG1r3PVhkjHuhdbP/di+EsfZCrU+sCB+8ROHSuYXK4YILVAnObBbXcqMYLC9TdwoH1AEVhTHGPcTBsvjUQfNE61Wy9b8=
    secret_access_key:
        secure: YMhLsFzfjfHtUepEI2apqdS0tINyMNnCyDZbDxm3snICUDweKDq0Pe8Z7s1Ynk6QZy0GBEC78VKJ7XCJRgu1wl3fhDh7iYcum5N1gy5bY/HTN1ppNsgwRFM46fqB4GPoxYSrhnQF3eoWp+bfCdTkcMasu1dbiAoDjVSVYlwPVRUmajqk9VuvF9GFUYqmqAizdPjZuoy0Pb4Kq9TczqEuqnF3moEO36UhI8CYerGBY9zfdyNHSLgIX+RqHTu4Kxq55tzqW6rUBPg8nPn+qWlpyxu8nhpCvFa8wgK4dA0tDhIUfZ7kU+8c+eHJQ926PlR3L4W+xz0KtXa9WMj4v723og/01ZJbeAYE/SQcmPwpmpYWZ4OI9fWRBP1gJUWZMGU+Z2Jwh1XEsOKs/Ktybs6pAh9GC5KaEi5Psx42xR6HZbiiEzZrGBwFnuDY+d08rXddObBypYafYHK4bc1fDRyV37RBxIGC+ci8B5uQPdBVm0HMTMMQX75q7B07jxtLK83g+XnPvE2ShKigzy53qiyPFwGje2yx3YrFvUl9ihxHqj6n3ExpAXV4fUyyc8+GHwg6c9mlb9ZXXSENFWmlcS7c+MSEobeV4lqdKc/ndIaSyC2QF8bEUUxNIgMIiN4lC2IXGWvjOA9kFJZNtp+jb8MVzFGsgzif+GtpsDi504RNh8c=
    bucket: aptrust.public.download
    cleanup: false
    local_dir: dist
    upload_dir: DART
    acl: public_read
    on:
      repo: APTrust/dart
