os: osx
osx_image: xcode9.2

dist: trusty
sudo: false

language: node_js
node_js: "9"
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - electron/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

environment:
  - GOPATH: c:\gopath
  - access_token:
        secure:  pJmtCY7+qzctn9m6UejaJGlls3IMl8p2Tb3DjypHL+8DLmNNHK0jQZmZbb4sIJgM
  - GH_TOKEN: "UNOjiHOiOW9ptFp5AT9VoP24kIkXiKTcRWf+3ijpkhO6uIdYy7HRq+ieOTqrpijtvYtv6BVa4Lx4lh9GPqMCQIJQ3BNOToAQneVCkxzWbTxa+/EwsySxTNNnmRoui9sTyUphZWh0x/xlYrS/bkN++xO3jnkNU5CjnaYjvidOsX/hbG//hJpO0FKfIFuvdZk4X2hBRm8WJthOWtlbdLwjCb8StI24fYy0Bwd5ulh1kcBpk1UZ1toGap7Ph4FBXKfadMae5KjvE5ktkO4j8sI66GCqt2Tjp+SwOpZW/KFPge05e6dIOPTdWlwlviW+HVE34Ef/H+ljyj7PlsSHiyGCNLI4L9rf1C8Ayb9jtzWr23ZXJWMUH6ELlBlIV9DFqr6/MfSVhal0LV2LrZOlWK/h+Jzrh3LYaymVKHkh1tXJi/J4Fcr6RSnTJGFgbk/HBFL8US4AYTAbGExKJDBr/JqjR2oxXEFXQvePX9e/F8V4VMfMSX+MavBhHSAcfK7y+Gd1X56NVEGBgxhD6Z9uRaXaXjjEvNsgRZIcUiMf1lfVXdDw4l6WuG66/HxrYLNhUQC5ZKRlIcveqStGpLXbsIYoBFqrdPHmgWPHuCqeS1NZqb0Hy4BOvDaGUVw/Jci+i/S00bEWuuV83Xl84zWTElXFwm0E/4SdcH/2qtfpF99rWgY="
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi

  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"


install:
  - yarn

before_script:
  - git lfs pull

script:
  # - npm install npm -g
  #- npm install --prefix ./electron electron-builder@next # force install next version to test electron-builder
  #- cd electron && npm install
  #- echo %PATH%
  #- echo %GOPATH%
  #- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  #- npm run --prefix ./electron
  #- cd electron && electron-builder .
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder -p never; fi

deploy:
  provider: releases
  api_key:
    secure: "UNOjiHOiOW9ptFp5AT9VoP24kIkXiKTcRWf+3ijpkhO6uIdYy7HRq+ieOTqrpijtvYtv6BVa4Lx4lh9GPqMCQIJQ3BNOToAQneVCkxzWbTxa+/EwsySxTNNnmRoui9sTyUphZWh0x/xlYrS/bkN++xO3jnkNU5CjnaYjvidOsX/hbG//hJpO0FKfIFuvdZk4X2hBRm8WJthOWtlbdLwjCb8StI24fYy0Bwd5ulh1kcBpk1UZ1toGap7Ph4FBXKfadMae5KjvE5ktkO4j8sI66GCqt2Tjp+SwOpZW/KFPge05e6dIOPTdWlwlviW+HVE34Ef/H+ljyj7PlsSHiyGCNLI4L9rf1C8Ayb9jtzWr23ZXJWMUH6ELlBlIV9DFqr6/MfSVhal0LV2LrZOlWK/h+Jzrh3LYaymVKHkh1tXJi/J4Fcr6RSnTJGFgbk/HBFL8US4AYTAbGExKJDBr/JqjR2oxXEFXQvePX9e/F8V4VMfMSX+MavBhHSAcfK7y+Gd1X56NVEGBgxhD6Z9uRaXaXjjEvNsgRZIcUiMf1lfVXdDw4l6WuG66/HxrYLNhUQC5ZKRlIcveqStGpLXbsIYoBFqrdPHmgWPHuCqeS1NZqb0Hy4BOvDaGUVw/Jci+i/S00bEWuuV83Xl84zWTElXFwm0E/4SdcH/2qtfpF99rWgY="
  file: electron/dist/DART-0.1.5.dmg
  skip_cleanup: true
  on:
    repo: APTrust/dart
    branch: 156094170-automate-build-release
