
os: osx
osx_image: xcode9.2

sudo: false

language: node_js
node_js: "9"
environment:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
  - electron/node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

environment:
  - access_token:
        secure:  pJmtCY7+qzctn9m6UejaJGlls3IMl8p2Tb3DjypHL+8DLmNNHK0jQZmZbb4sIJgM
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi

install:
  - yarn

before_script:
<<<<<<< HEAD
  - git lfs pull

script:
  - if [[ "$TRAVIS_BRANCH" == "refactor" ]]; then cd refactor && npm test && cd ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn ; fi
  - buildver="$(grep version electron/package.json |sed "s/[^0-9.]//g").$(git log --format=%h -1)"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder -p never --em.version=$buildver; fi

before_deploy:
      - git config --local user.name "APTdeploy"
      - git config --local user.email "ops@aptrust.org"
      - git tag "v$(grep version electron/package.json |sed 's/[^0-9.]//g').$(git log --format=%h -1).$TRAVIS_BUILD_NUMBER"
=======
- git lfs pull
script:
- if [[ "$TRAVIS_BRANCH" == "refactor" ]]; then cd refactor && npm test && cd ..;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd electron && yarn; fi
- buildver="$(grep version electron/package.json |sed "s/[^0-9.]//g").$(git log --format=%h
  -1)"
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd electron && yarn && electron-builder
  -p never --em.version=$buildver; fi
addons:
  artifacts:
    working_dir: dist
    paths:
    - $(git ls-files -o dist/{*.dmg,*.exe,*.deb} | tr "\n" ":")
    target_paths:
    - "/app/build-${TRAVIS_BUILD_NUMBER}_commit-${TRAVIS_COMMIT:0:7}$([ ! -z ${TRAVIS_TAG}
      ] && echo _tag-${TRAVIS_TAG})"
    - DART/DART-$buildver.dmg
    bucket: aptrust.public.download
    key: AKIAIN34AYPE5DX5EJUQ
    secret:
      secure: eOwbN81+m8xAntNpef0zDMrsz6ZzEry9ZRvnxjvL9izpo9IlIAPwlPtDrLMlAv9Nf1g1WJvAUt25NelSRoApLsBbSZohdyMyy0AlC+KiyXv6sHVMhzmZQ2WFPg/atQkg+WwxQsizRur2VWaqR0Ke2K0cFmlo0HZm+w3iEJt8Y8lGewsAe9AcHLoxd8hFtABnijfeHq0fUzzLSgpdme9UTDGgO3HSj7I4B01+Rfq00W5u3RPZVqqff8bErQKC+8ZAYC1HAgM3FnK/m+vzwNkOl6m9t5xiUiNXGCaCb3/zRR8ZH/snFup8xKJwikNfLlxGkEpkfH+mlcNzER3e3xRF3m2eZO410spoLa/9PkI5GRfv2ZX+tm8mNpqZjU5v1BHmsirdspzJ2uVTH456yM2RfS46M202OuX7W1i7HMmliRNRNgvvsYnNqgSxiPI2283xJxSmfn0UysuMe4he+zVM5SIqu6Bhx0zrrSw9oLP4vTCYjnzlNMFqDcxlsjLOfi1aCM8fxnEBCSupHbEMTIqSNfL7lMqhBiGbHp0CUVWuj37Z7BAjZLmvtndV25Ju3AnOOMybzk+6KpKZhGwdYQWnN48Z28r3kqKyZESdx44Z+LA8SxRuiOBqvL/R0qCcZfqATxvmW+aPkFj9cjASro92WWVR8niNg2v7aLXXH1GJIEQ=
>>>>>>> af68983d... sudo make me a Travis Slacker
deploy:
  provider: releases
  api_key:
    secure: 1RQHlxSWvh7QFV1rAhPnd+0bNWDPOV6XVbBoFXA1Oa2nXKthjBkmc4OTo2CNFpC1k1Wn4zW8SAduzMr9jG9f2HG+imWsy6IkRh3wUMLcE9RgfYDmaFOfwhqbjtoS+dQhBis3kI5YmhLDOaCD7BDuVttVGil8ZMpcGY1xWVPgBQRFlE71IssNEyOfxYhl1/njoT4nEaL/s/C5P+p1fKc+HlbdLpdpfnYRDs90NpqZuJKM4JzNWIECWoZqZY94cPLe9Czog1ijZvJbCQ0yGXOE70yWQN5KE9yk40JVbBdOBcfgzgbyAFCl+xvVj6v4TRuqRDL6tsF8SahPNdSdme0lOl8hegxeWfzmCjanY/Qnuh1Jk+JYy0hmUiLZgm+KPAjW0+LgFhPSO7QpPUA13UAWf05JrnvRIAyC0jfw48kQjuxd85cT1jQ8v6aii+m1GxbIOTsifBdG87b5dASN8ykSQUDT6UhOBbXplR6fwD2qM6UZa9TqiFhmvce12Jojff8BeUq8ZsXDo776PII9djJxE9z3SOkSg+omXn0DoRkt5gghdix+t5q5lmezUMBaTp3k+ozb8CO1rDzKqSfzQ8KEGUms/UGZi+NBbMbcwgCFJODykNOnnS6Mk0n+ztsj63x7t59nQuavsG4E8RS1888bPC1dncBMGjZqA/wthw+NRcw=
  file_glob: true
  file: electron/dist/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: master

notifications:
  slack:
    secure: fYGIkZMYp/HhRhi4/6Q1jpv0nWfpZaqaIKRhhloi+kBIt2fFun49LmTQfjqGLfwKKCKNmx8XzdIASUZuW7auJhHLUZPWaeEDxQjNVjrSOKOUuFUeGCKRJtw6+la0VxT79y5YIWxrnY2Noi8I6NvxniAJwnyQlHdyCnavmZzTA2xQGHxfTI4PR3ZkFt6lVAEC09NZMYwUf5+jsFmR6k/NGBU0jotDkfsm7AdzADSHwqfGvi70V9+muG4DIJejRVOkyCka2EOixbAyOOzbvrDwOo8tZVbY6Ch0LCfYndbDIztWXWb34R8LQEVKJA6QV2qMHmqSyMmR1RUO/OmMDmq+kM4C3M3D91knrugFVJiLJeowj8cb5LKgX35cd8/dHCDnLkSuaAw+rk5ny3TzfX2uh/EI9QN8y7S+er+QNvumy3M1+pkT+M+7t+auu0l7Ab+G/8W5X0PrZaQ+M933tYy1FC0zrp+CNs6BQnVvpql7REISJuuZ3T950FCxLM09XDGTnqxkgo8NrunuHcFgr8Jo74dl4TiixJteCVTOYI46KvfWDDlByKRmYb8GpQOXY4TT0dH5eEOjbcF3OFSQrx0aiC2TA6sTVHzvRqHdjjDGv2IXcJUJyLMnXrUsMVl4MuDCWGsqwKSEh71mflkreSc4yZ17M5ZEUBh90/dA9eICk9c=
